### ISSUE TITLE
发布到HACS / Publish to HACS 

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [cozylife/hass_cozylife_local_pull#21]
如果使用HACS的话，安装过程将会方便快捷很多。

If published to Home Assistant Community Store (HACS), it would be easier and quicker to install.

https://hacs.xyz/

https://hacs.xyz/docs/publish/start#general-requirements

------

P.S. 中英双语皆可。 I can communicate in both Chinese and English.

**Comment by cozylife** [comment]
你好。
我已经准备开始开始新的集成了，新的集成在刚发布时不会考虑发布到hacs，在成熟之后会发布到hacs。
另外，该repo是MIT；你可以fork repo然后提交到hacs。

**Comment by SodaWithoutSparkles** [comment]
Translation:

> 你好。
Hello.

> 我已经准备开始开始新的集成了，新的集成在刚发布时不会考虑发布到hacs，在成熟之后会发布到hacs。
I am preparing for another integration. The new integration wont be published to HACS at first, until the project is mature enough.

> 另外，该repo是MIT；你可以fork repo然后提交到hacs。
Other than that, the new repo would be MIT licensed. You could fork the repo and publish to HACS.
