### ISSUE TITLE
Cozy Smartswitch only have on-off option

### ISSUE THREAD

**Issue by alexwun96** [cozylife/hass_cozylife_local_pull#23]
team, i want to check with you when will the version that is able to view the power consumption be released?  As one of the reasons i bought the smart socket is want to use it to detect the washing machine finishing the laundry.

**Comment by andreescocard** [comment]
Probably never and this feature has nothing to do with this repo.

**Comment by cozylife** [comment]
Hello.
This function depends on user permissions and will be implemented in another integration.

**Comment by cozylife** [comment]
> Probably never and this feature has nothing to do with this repo.

You are right.
