### ISSUE TITLE
Unable to Add CozyLife Plugin to Home Assistant

### ISSUE THREAD

**Issue by Jermen11870** [cozylife/hass_cozylife_local_pull#25]
I am encountering with the integration of the CozyLife plugin into Home Assistant.

Upon adding the following line to my configuration.yaml file:
hass_cozylife_local_pull:

and subsequently restarting Home Assistant, I followed the provided instructions to add the "cozylife" plugin through the "Add Integration" menu. However, despite locating the "cozylife" plugin, I am unable to successfully integrate it with Home Assistant. The screenshot below illustrates the problem:

<img width="718" alt="螢幕截圖 2023-11-18 下午1 08 57" src="https://github.com/cozylife/hass_cozylife_local_pull/assets/149940662/ced3978b-b354-4a08-ad3c-cfc598d5433d">

Could you kindly assist me in resolving this issue or provide guidance on how to successfully integrate the CozyLife plugin into Home Assistant? Your prompt attention to this matter would be greatly appreciated.

**Comment by kozfelipe** [comment]
this repo is buggy and has no replies. I suggest you to use this fork https://github.com/yangqian/hass-cozylife

**Comment by cozylife** [comment]
Hello.
You may need to restart your device multiple times.

**Comment by hardy2408** [comment]
This repo was working for me in the former HA version for a LED strip.
After upgrading to HA 2024.3.3 it is no longer working, and I also don't see any error messages.
The mentioned [https://github.com/yangqian/hass-cozylife] is also not working for me, does not detect the device.

**Comment by cozylife** [comment]
Hello.
Please use the latest version to try.
