### ISSUE TITLE
This entity is no longer being provided by the hass_cozylife_local_pull integration. If the entity is no longer in use, delete it in settings.

### ISSUE THREAD

**Issue by ojoojoo** [cozylife/hass_cozylife_local_pull#26]
This worked perfectly untill today, what's wrong?
I restarted HA a few times and still not working.
In the cozylife app it's still working.

This entity is no longer being provided by the hass_cozylife_local_pull integration. If the entity is no longer in use, delete it in settings.

**Comment by cozylife** [comment]
Hello.
There are indeed some issues with the functionality of this repository. I'm already preparing to develop new code to support haas.
You can try multiple times.

**Comment by SobujCh** [comment]
same here. any temporary solution until this is fixed?

**Comment by superclaw** [comment]
today it happened for my hass too. Any solution?

**Comment by ojoojoo** [comment]
I threw the cozylife switches in the bin and got new Tuya compliant versions on Ali for 1,88€ each😬👍

**Comment by superclaw** [comment]
> I threw the cozylife switches in the bin and got new Tuya compliant versions on Ali for 1,88€ each😬👍

I think so too

**Comment by Scobber** [comment]
all my cozy switches were HomeKit as well. so I used the cozy app to connect them to the network then adopted them with the HomeKit device integration. works way better then local cozy
