### ISSUE TITLE
smart plug support power consumption monitoring?

### ISSUE THREAD

**Issue by charliechan53** [cozylife/hass_cozylife_local_pull#33]
smart plug support power consumption monitoring?

**Comment by cozylife** [comment]
Hello.
Not currently supported.
At the same time, this repository will not support this feature.
If you want to support this function and need to use the server's functions, I will open a new code repository to implement it.

**Comment by charliechan53** [comment]
please open a new code repository for server functions and let see how to implement this for energy monitoring inter

**Comment by cozylife** [comment]
Hello.
I don't have the energy to do it.
Processing will not begin anytime soon.
