### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ryangonzalez133** [cozylife/hass_cozylife_local_pull#5]
Error!

**Comment by johnypony3** [comment]
please learn to file better bug reports, we understand you are frustrated.

**Comment by cozylife** [comment]
Hi.
I suggest you describe the problem in detail.

**Comment by ryangonzalez133** [comment]
Sometimes my Cozylife device just disconnects from Home assistant going offline, when restarting Home assistant the device returns as online.
Other times I get the alert in the HA logs like this "Updating state for light.cozylife_smart_bulb_light (<class 'custom_components.hass_cozylife_local_pull.light.CozyLifeLight'>) took 1,286 seconds. Please report it to the custom integration author."

**Comment by cozylife** [comment]
Hi.
This requires implementing a reconnect feature, which will be implemented in the next version.
